### ISSUE TITLE
Support dataFrom="STORE_OR_NETWORK", matching <QueryLookupRenderer>

### ISSUE THREAD

**Issue by damassi** [relay-tools/found-relay#138]
I've started experimenting with `found-relay` and noticed that when transitioning between routes a request is being sent rather than pulling from the store cache:

![rereq](https://user-images.githubusercontent.com/236943/40211709-02f4f032-5a01-11e8-9cd5-c007a59b8a1b.gif)

This seems like the correct behavior, but it would be nice to have a `lookup` option (similar to `QueryLookupRenderer`) so that transitions can remain snappy after the initial data set has been loaded and stored. (Being able to pass in an `expire` time would also be nice.)

Also, noticed this [`cacheConfig`](https://github.com/4Catalyzer/found-relay/blob/master/src/modern/Resolver.js#L38) prop, but can't seem to track down how it's being used, or whether it would be appropriate to piggyback on this to achieve lookup behavior.

**Comment by taion** [comment]
`cacheConfig` doesn't really do anything. It just gets forwarded to the network layer. The network layer then implements the semantics – so if you had caching in the network layer, it could in principle control that, but I can understand not wanting request caching, because blowing away your whole cache on every mutation sort of sucks, plus it takes some time for the store to normalize those responses anyway.

I think the right API here is to add a `lookup` prop (and `getLookup`). A fancier API would be to make the query fetcher parametrizable, except `ReactRelayQueryFetcher` isn't exported, and it seems like too much effort to vendor that in.

**Comment by damassi** [comment]
Would approaching this similar to how its done in [`QueryLookupRenderer`](https://github.com/relay-tools/relay-query-lookup-renderer/blob/master/src/index.js#L118-L123) be the appropriate way to handle this?

**Comment by taion** [comment]
Yup, exactly so, though the code is structured a bit differently here, since we need to tap into the loading state in the resolver to synchronize loading across routes. I have an overdue task to clean some of this up that I've been putting off because it hasn't caused any visible problems yet: https://github.com/4Catalyzer/found-relay/issues/89.

Might get a chance to look at this later next week.
