### ISSUE TITLE
RouteConfig

### ISSUE THREAD

**Issue by soneymathew** [relay-tools/found-relay#145]
Hello @taion ,

I built a Relay modern App with the following hierarchy
- QueryRenderer
  - RefetchContainer
     - PaginationContainer
       - FragmentContainer

and it works fine. It has only one route at the moment

I am trying to replace QueryRenderer with a found route (`found/lib/Route`) and also using
`import { Resolver } from 'found-relay';`

The Query aggregation happens fine, I can see that the params from the route are used as variables values send to the GraphQL endpoint, and data is returned just the way I need it

But I notice that the `data` prop is not spread to the React components.
```
Warning: createFragmentSpecResolver: Expected prop `mydata` to be supplied to `Relay(MyApp)`, but got `undefined`. Pass an explicit `null` if this is intentional.
```

Please let me know, if this is a known issue. or wrong usage of the router.

I am using the following versions
        "farce": "^0.2.6",
        "found": "^0.3.11",
        "found-relay": "0.3.0-alpha.13",

Thanks,
Soney

**Comment by soneymathew** [comment]
Is the presence of a viewer node required for the props to be distributed?

If I modify this query 
https://github.com/relay-tools/found-relay/blob/master/examples/todomvc-modern/src/routes.js#L22-L26

and redefine it as
```
      query routes_TodoApp_Query {
          ...TodoApp
      }
```

will it work with `found-relay`?

I don't have a viewer type in my schema.

**Comment by soneymathew** [comment]
Looks like my understanding of found-relay was incorrect.
I assumed that the root route will aggregate the queries of the nested routes, didn't know each route is a [QueryRenderer](https://github.com/relay-tools/found-relay/issues/56#issuecomment-360856801) by itself.

I will wait for the [docs](https://github.com/relay-tools/found-relay/issues/56) to be flushed out before getting back to using this :( for now I am not able to recommend this to my team, 

I am able to proceed further in my POC with react-router v4 by using a single QueryRenderer for the route. I prepare variables for my query based on the params in the route

**Comment by taion** [comment]
Sorry for the trouble you had.

It is in fact the case that each `<Route>` behaves as if it were an independent `<QueryRenderer>`. This is consistent with the earlier design of react-router-relay, and it's worked for us so far.

As such, the behavior of `query` and `render` is essentially identical to that where you use a `<QueryRenderer>`, and things work the same way. If you use a masked fragment, you must pass that down. If you want to access values in `render`, you must include them explicitly in the `query` (or use an unmasked fragment).

The benefit arises when nested query renderers would otherwise be used.
